name: Testing of context

on:
  push:
    branches:
      - ex15-16
  pull_request:
    branches: [master]
    types: [opened, synchronize]

jobs:
  a_test_job:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Github context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
      - name: Commits
        env:
          COMMITS: ${{ toJson(github.event.commits) }}
        run: |
          echo "$COMMITS"
      - name: Commit messages
        env:
          COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
        run: |
          echo "$COMMIT_MESSAGES"
