name: Health check

on:
  schedule:
    - cron: '0/3 * * * *'

jobs:
  periodic_health_check:
    runs-on: ubuntu-20.04
    steps:
      - name: Ping the deployed service URL
        uses: jtalk/url-health-check-action@v3
        with:
          url: https://full-stack-open-pokedex-9j7j.onrender.com/health
          max-attempts: 2
          retry-delay: 60s
